server.port: 10002

solon.app:
  name: 'solon-a2a-server2'

solon.logging:
  appender:
    console:
      level: DEBUG

solon.ai:
  demo:
    apiUrl: "http://127.0.0.1:11434/api/chat"
    provider: "ollama"
    model: "qwen2.5:latest"